2024-05-29 08:48:01,873 - DFI => Execução iniciada
2024-05-29 08:48:01,895 -     => Main - Execução iniciada
2024-05-29 08:48:01,895 -     => balancasp6000 - Execução iniciada
2024-05-29 08:48:03,181 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-05-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-05-29 08:48:03,238 -     => balancasp6000 - Execução concluída
2024-05-29 08:48:03,239 -     => Main - Execução concluída
2024-05-29 08:50:03,307 -     => Main - Execução iniciada
2024-05-29 08:50:03,308 -     => balancasp6000 - Execução iniciada
2024-05-29 08:50:03,834 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-05-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-05-29 08:50:03,875 -     => balancasp6000 - Execução concluída
2024-05-29 08:50:03,875 -     => Main - Execução concluída
2024-05-29 08:52:03,939 -     => Main - Execução iniciada
2024-05-29 08:52:03,939 -     => balancasp6000 - Execução iniciada
2024-05-29 08:52:04,486 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-05-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-05-29 08:52:04,519 -     => balancasp6000 - Execução concluída
2024-05-29 08:52:04,519 -     => Main - Execução concluída
2024-05-29 08:54:04,588 -     => Main - Execução iniciada
2024-05-29 08:54:04,588 -     => balancasp6000 - Execução iniciada
2024-05-29 08:54:06,744 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-05-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-05-29 08:54:06,789 -     => balancasp6000 - Execução concluída
2024-05-29 08:54:06,789 -     => Main - Execução concluída
2024-05-29 08:56:06,860 -     => Main - Execução iniciada
2024-05-29 08:56:06,860 -     => balancasp6000 - Execução iniciada
2024-05-29 08:56:08,092 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-05-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-05-29 08:56:08,291 -     => balancasp6000 - Execução concluída
2024-05-29 08:56:08,291 -     => Main - Execução concluída
2024-05-29 08:58:08,365 -     => Main - Execução iniciada
2024-05-29 08:58:08,365 -     => balancasp6000 - Execução iniciada
2024-05-29 08:58:08,776 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-05-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-05-29 08:58:08,817 -     => balancasp6000 - Execução concluída
2024-05-29 08:58:08,817 -     => Main - Execução concluída
2024-05-29 09:07:19,648 - DFI => Execução iniciada
2024-05-29 09:07:19,664 -     => Main - Execução iniciada
2024-05-29 09:07:19,664 -     => balancasp6000 - Execução iniciada
2024-05-29 09:07:20,744 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-05-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-05-29 09:07:20,782 -     => balancasp6000 - Execução concluída
2024-05-29 09:07:20,782 -     => Main - Execução concluída
2024-05-29 09:09:20,852 -     => Main - Execução iniciada
2024-05-29 09:09:20,852 -     => balancasp6000 - Execução iniciada
2024-05-29 09:09:21,406 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-05-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-05-29 09:09:21,518 -     => balancasp6000 - Execução concluída
2024-05-29 09:09:21,518 -     => Main - Execução concluída
2024-05-29 09:11:42,327 - DFI => Execução iniciada
2024-05-29 09:11:42,339 -     => Main - Execução iniciada
2024-05-29 09:11:42,339 -     => balancasp6000 - Execução iniciada
2024-05-29 09:11:42,878 -       => Error:       (X) tools.py.[verifyFile]: O arquivo dfi_balancasp6000_log-2024-05-29.log não foi encontrado no caminho D:\Development\Python\dfi\arquivos-historico\balancasp6000.: 
2024-05-29 09:11:42,914 -     => balancasp6000 - Execução concluída
2024-05-29 09:11:42,914 -     => Main - Execução concluída
2024-05-29 09:11:42,914 - DFI => Execução encerrada
2024-05-29 12:23:41,188 - DFI => Execução iniciada
2024-05-29 12:23:41,211 -     => Main - Execução iniciada
2024-05-29 12:23:41,211 -     => avacorp - Execução iniciada
2024-05-29 12:24:03,334 -       => Error:       (X) connectDatabase.py.[connectDatabase]: Conexão com Origem: Server:Database:[168.75.71.21:dftransportes]:: (psycopg2.OperationalError) connection to server at "168.75.71.21", port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-05-29 12:28:50,507 - DFI => Execução iniciada
2024-05-29 12:28:50,516 -     => Main - Execução iniciada
2024-05-29 12:28:50,517 -     => avacorp - Execução iniciada
2024-05-29 12:29:06,675 -     => avacorp - Execução concluída
2024-05-29 12:29:06,679 -     => Main - Execução concluída
2024-05-29 12:29:06,679 - DFI => Execução encerrada
