2024-04-30 13:39:44,701 - DFI => Execução iniciada
2024-04-30 13:39:44,727 -     => Main - Execução iniciada
2024-04-30 13:39:44,728 -     => commodities - Execução iniciada
2024-04-30 13:41:23,753 - DFI => Execução iniciada
2024-04-30 13:41:23,766 -     => Main - Execução iniciada
2024-04-30 13:41:23,766 -     => commodities - Execução iniciada
2024-04-30 13:44:38,053 - DFI => Execução iniciada
2024-04-30 13:44:38,061 -     => Main - Execução iniciada
2024-04-30 13:44:38,061 -     => commodities - Execução iniciada
2024-04-30 13:45:08,836 - DFI => Execução iniciada
2024-04-30 13:45:08,844 -     => Main - Execução iniciada
2024-04-30 13:45:08,845 -     => commodities - Execução iniciada
2024-04-30 13:45:09,046 -       => Error:       (X) importDatabaseToDataframe.py.[importDatabaseToDataframe]: Erro ao importar informações do(s) database(s) de Destino:: 'DatabaseDestinyInfo' object has no attribute 'get_addressDestiny'
2024-04-30 13:46:07,997 - DFI => Execução iniciada
2024-04-30 13:46:08,005 -     => Main - Execução iniciada
2024-04-30 13:46:08,005 -     => commodities - Execução iniciada
2024-04-30 13:47:22,633 - DFI => Execução iniciada
2024-04-30 13:47:22,658 -     => Main - Execução iniciada
2024-04-30 13:47:22,659 -     => commodities - Execução iniciada
2024-04-30 13:49:20,007 -       => Error:       (X) connectFile.py.[connectFile]: Conexão com Origem:: 'DataItem' object has no attribute 'get_name'
2024-04-30 13:49:49,685 - DFI => Execução iniciada
2024-04-30 13:49:49,710 -     => Main - Execução iniciada
2024-04-30 13:49:49,711 -     => commodities - Execução iniciada
2024-04-30 13:50:47,412 - DFI => Execução iniciada
2024-04-30 13:50:47,436 -     => Main - Execução iniciada
2024-04-30 13:50:47,437 -     => commodities - Execução iniciada
2024-04-30 13:51:30,749 -       => Error:       (X) importXlsToDataframe.py.[importXlsSeriesToDataframe]: Importação de arquivos em série Xlsx para Dataframe principal:: 'DataItem' object has no attribute 'get_name'
2024-04-30 13:54:56,916 - DFI => Execução iniciada
2024-04-30 13:54:56,945 -     => Main - Execução iniciada
2024-04-30 13:54:56,946 -     => commodities - Execução iniciada
2024-04-30 16:21:54,048 - DFI => Execução iniciada
2024-04-30 16:21:54,064 -     => Main - Execução iniciada
2024-04-30 16:21:54,065 -     => commodities - Execução iniciada
2024-04-30 16:21:55,555 -       => Error:       (X) importXlsToDataframe.py.[importXlsSeriesToDataframe]: Importação de arquivos em série Xlsx para Dataframe principal:: 'DataItem' object has no attribute 'get_name'
2024-04-30 16:25:04,796 - DFI => Execução iniciada
2024-04-30 16:25:04,821 -     => Main - Execução iniciada
2024-04-30 16:25:04,823 -     => commodities - Execução iniciada
2024-04-30 16:26:23,711 -       => Error:       (X) importXlsToDataframe.py.[importXlsSeriesToDataframe]: Importação de arquivos em série Xlsx para Dataframe principal:: 'DataItem' object has no attribute 'get_name'
2024-04-30 16:26:41,750 - DFI => Execução iniciada
2024-04-30 16:26:41,758 -     => Main - Execução iniciada
2024-04-30 16:26:41,758 -     => commodities - Execução iniciada
2024-04-30 16:26:45,732 - DFI => Execução iniciada
2024-04-30 16:26:45,758 -     => Main - Execução iniciada
2024-04-30 16:26:45,758 -     => commodities - Execução iniciada
2024-04-30 16:27:17,408 -       => Error:       (X) importXlsToDataframe.py.[importXlsSeriesToDataframe]: Importação de arquivos em série Xlsx para Dataframe principal:: 'DataItem' object has no attribute 'get_name'
2024-04-30 16:27:37,080 - DFI => Execução iniciada
2024-04-30 16:27:37,107 -     => Main - Execução iniciada
2024-04-30 16:27:37,108 -     => commodities - Execução iniciada
2024-04-30 16:27:40,010 -       => Error:       (X) importXlsToDataframe.py.[importXlsSeriesToDataframe]: Importação de arquivos em série Xlsx para Dataframe principal:: 'DataItem' object has no attribute 'get_name'
2024-04-30 16:27:46,911 - DFI => Execução iniciada
2024-04-30 16:27:46,937 -     => Main - Execução iniciada
2024-04-30 16:27:46,938 -     => commodities - Execução iniciada
2024-04-30 16:27:54,870 -       => Error:       (X) importXlsToDataframe.py.[importXlsSeriesToDataframe]: Importação de arquivos em série Xlsx para Dataframe principal:: 'DataItem' object has no attribute 'get_name'
2024-04-30 16:28:09,737 - DFI => Execução iniciada
2024-04-30 16:28:09,745 -     => Main - Execução iniciada
2024-04-30 16:28:09,745 -     => commodities - Execução iniciada
2024-04-30 16:28:10,852 -       => Error:       (X) importXlsToDataframe.py.[executeImportXlsToDataframe]: Erro durante a importação de dados:: 'DataItem' object has no attribute 'get_name'
2024-04-30 16:28:28,889 - DFI => Execução iniciada
2024-04-30 16:28:28,916 -     => Main - Execução iniciada
2024-04-30 16:28:28,917 -     => commodities - Execução iniciada
2024-04-30 16:28:56,265 -       => Error:       (X) importXlsToDataframe.py.[executeImportXlsToDataframe]: Erro durante a importação de dados:: 'DataItem' object has no attribute 'get_name'
2024-04-30 16:29:31,663 - DFI => Execução iniciada
2024-04-30 16:29:31,689 -     => Main - Execução iniciada
2024-04-30 16:29:31,690 -     => commodities - Execução iniciada
2024-04-30 16:29:32,928 -       => Error:       (X) importXlsToDataframe.py.[executeImportXlsToDataframe]: Erro durante a importação de dados:: 'DataItem' object has no attribute 'get_name'
2024-04-30 16:30:10,133 - DFI => Execução iniciada
2024-04-30 16:30:10,158 -     => Main - Execução iniciada
2024-04-30 16:30:10,159 -     => commodities - Execução iniciada
2024-04-30 16:31:35,043 -     => commodities - Execução concluída
2024-04-30 16:31:35,058 -     => avacorp - Execução iniciada
2024-04-30 16:31:37,173 -       => Error:       (X) connectDatabase.py.[connectDatabase]: Conexão com Origem: Server:Database:[168.75.71.21:dftransportes]:: 'DatabaseSourceInfo' object has no attribute 'get_addressDestiny'
